/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SuperPos;

import javax.swing.table.TableModel;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
    }
    
    String lsub;
    String lpay;
    String lbal;
    
    
    
 public Print(String sub, String pay, String bal, TableModel tableModel) {
    initComponents();

    this.lsub = sub;
    this.lpay = pay;
    this.lbal = bal;

    txtprint.setText("");
    txtprint.setText(txtprint.getText() + "****************************************************\n");
    txtprint.setText(txtprint.getText() + "**************  Tharushika Sweets  **************\n");
    txtprint.setText(txtprint.getText() + "****************************************************\n");
    txtprint.setText(txtprint.getText() + "             Receipt\n");
    txtprint.setText(txtprint.getText() + "------------------------------------------------\n");
    txtprint.setText(txtprint.getText() + "Product         Price        Qty       Total\n");
    txtprint.setText(txtprint.getText() + "------------------------------------------------\n");

    for (int i = 0; i < tableModel.getRowCount(); i++) {
        String product = (String) tableModel.getValueAt(i, 1); // Product name is a String
        String price = tableModel.getValueAt(i, 2).toString(); // Convert price to String
        String quantity = tableModel.getValueAt(i, 3).toString(); // Convert quantity to String
        String total = tableModel.getValueAt(i, 4).toString(); // Convert total to String

        // Align the text to fit the format
        txtprint.setText(txtprint.getText() + String.format("%-15s %-10s %-10s %-10s\n", product, price, quantity, total));
    }

    txtprint.setText(txtprint.getText() + "------------------------------------------------\n");
    txtprint.setText(txtprint.getText() + String.format("%-25s %15s\n", "Subtotal:", sub));
    txtprint.setText(txtprint.getText() + String.format("%-25s %15s\n", "Pay:", pay));
    txtprint.setText(txtprint.getText() + String.format("%-25s %15s\n", "Balance:", bal));
    txtprint.setText(txtprint.getText() + "------------------------------------------------\n");
    txtprint.setText(txtprint.getText() + "****************************************************\n");
    txtprint.setText(txtprint.getText() + "*************  Thank You! Come Again  ***********\n");
    txtprint.setText(txtprint.getText() + "****************************************************\n");

    // Attempt to print the receipt
    try {
        txtprint.print();
    } catch (PrinterException ex) {
        Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(210, 307));

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
